### ISSUE TITLE
UI: Style the layer menu

### ISSUE THREAD

**Issue by pettter** [DCMLab/reductive_analysis_app#149]
The layer menu should be styled according to the Figma.

**Comment by meduzen** [comment]
Is there a JSON sample I can use to test “draw tree (from JSON)”?

**Comment by yrammos** [comment]
@meduzen, @pettter just pushed a PR (#190) which addresses a breaking issue with harmony trees. You'll need to pull that in in order to test trees.

Once you've done so, you can use the JSON he provided.

To display the tree, select any three secondaries in the score and click on the "Align" button.

**Comment by meduzen** [comment]
Thanks for the instructions, @yrammos! PR merged.
